### PR TITLE
Add example Forwarder configuration

### LINKED ISSUE #28: Request: Add docker compose example for Graylog-Forwarder
It would be very helpful to include a reference or example docker compose file for using Graylog-forwarder with docker. Currently there does not appear to be anything documented on how to correctly do this.

### PR DESCRIPTION
**Pull request by bernd**
Fixes #28

### CODE REVIEW

**Comment by drewmiranda-gl** [comment]
Looks great! The only thing i might add is setting the node-id. I'm certainly not a docker expert, i did this using a read_only bind volume, but not sure if there is a better way:

```
    volumes:
      - type: bind
        source: ./node-id
        target: /data/node-id
        read_only: true
```

Change to suite taste (e.g. to cooincide with `GRAYLOG_NODE_ID_FILE`)

It would be killer to be able to set this as a env var (vs a file) but maybe that should be opened as a feature req? :)

**Comment by bernd** [comment]
> Looks great! The only thing i might add is setting the node-id. I'm certainly not a docker expert, i did this using a read_only bind volume, but not sure if there is a better way:
> 
> ```
>     volumes:
>       - type: bind
>         source: ./node-id
>         target: /data/node-id
>         read_only: true
> ```
> 
> Change to suite taste (e.g. to cooincide with `GRAYLOG_NODE_ID_FILE`)
> 
> It would be killer to be able to set this as an env var (vs a file) but maybe that should be opened as a feature req? :)

Why would you want to set the node ID explicitly? The container stores the node ID on the persistent volume so it doesn't change between service restarts.

**Comment by BlueTeamNinja** [comment]
Unless I've misconfigured,
I've had to set the node ID on every forwarder or it is registered as a new forwarder every time it restarts or you upgrade.

I actually thought it was intended behaviour.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by drewmiranda-gl** [comment]
That was exactly the behavior i observed in testing. BUT It appears the way to address is the super secret `GRAYLOG_NODE_ID_FILE: "/var/lib/graylog-forwarder/node-id"` environment.

Coupled with

```
volumes:
  - "forwarder-data:/var/lib/graylog-forwarder"
```

so i guess its a question of are we doing it right or are we fixing a "problem" in the wrong way?

**Comment by bernd** [comment]
A new graylog-forwarder image containing the fix is pushed.

**Pull request merged**
